uav_mpc_node:
  ros__parameters:
    # Type of trajectory to follow: "hold" or "circle"
    trajectory_type: "circle"

    # Enable/Disable physical model and constraints of the tether
    use_tether: false

    # Circular trajectory parameters
    circle_radius: 3.0
    circle_omega: 0.2
    circle_height: 10.0

    # Hold mode height
    hold_height: 7.0     # Target hovering altitude in hold mode (m)

    # Takeoff height (used by PX4 takeoff command and state machine checks)
    takeoff_height: 4.0


    # Dynamic physical limits of the drone (less aggressive settings)
    v_max: 5.0           # Maximum velocity (m/s)
    u_max: 12.5          # Maximum thrust acceleration (m/s^2)
    hover_throttle: 0.7265 # Normalized hover throttle command
    tilt_max: 0.4        # Maximum tilt angle (rad, ~11.5 deg)
