<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>test_cooperative_mpc</name>
  <version>0.0.0</version>
  <description>Cooperative UAV-USV MPC test mission package</description>
  <maintainer email="tomas@todo.todo">tomas</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>uav_mpc</depend>
  <depend>usv_mpc</depend>
  <depend>test_uav_circle</depend>
  <depend>test_usv_circle</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
