/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) uav_tethered_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {6, 6, 1};
static const casadi_int casadi_s2[3] = {6, 3, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};

/* uav_tethered_expl_vde_forw:(i0[6],i1[6x6],i2[6x3],i3[3],i4[6])->(o0[6],o1[6x6],o2[6x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[3]? arg[3][0] : 0;
  a01=arg[4]? arg[4][3] : 0;
  a02=arg[4]? arg[4][4] : 0;
  a03=arg[4]? arg[4][0] : 0;
  a04=arg[0]? arg[0][0] : 0;
  a03=(a03-a04);
  a04=casadi_sq(a03);
  a05=arg[4]? arg[4][1] : 0;
  a06=arg[0]? arg[0][1] : 0;
  a05=(a05-a06);
  a06=casadi_sq(a05);
  a04=(a04+a06);
  a06=arg[4]? arg[4][2] : 0;
  a07=arg[0]? arg[0][2] : 0;
  a06=(a06-a07);
  a07=casadi_sq(a06);
  a04=(a04+a07);
  a07=arg[4]? arg[4][5] : 0;
  a07=casadi_sq(a07);
  a04=(a04+a07);
  a04=sqrt(a04);
  a07=(a02*a04);
  a01=(a01+a07);
  a07=2.0600000000000001e+00;
  a01=(a01/a07);
  a07=(a03/a04);
  a08=(a01*a07);
  a00=(a00+a08);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[3]? arg[3][1] : 0;
  a08=(a05/a04);
  a09=(a01*a08);
  a00=(a00+a09);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[3]? arg[3][2] : 0;
  a09=-9.8100000000000005e+00;
  a00=(a00+a09);
  a09=(a06/a04);
  a10=(a01*a09);
  a00=(a00+a10);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][0]=a00;
  a00=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][1]=a00;
  a00=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a00;
  a00=(a07/a04);
  a03=(a03+a03);
  a10=arg[1]? arg[1][0] : 0;
  a11=(a03*a10);
  a05=(a05+a05);
  a12=arg[1]? arg[1][1] : 0;
  a13=(a05*a12);
  a11=(a11+a13);
  a06=(a06+a06);
  a13=arg[1]? arg[1][2] : 0;
  a14=(a06*a13);
  a11=(a11+a14);
  a14=(a04+a04);
  a11=(a11/a14);
  a15=(a00*a11);
  a10=(a10/a04);
  a15=(a15-a10);
  a15=(a01*a15);
  a10=4.8543689320388350e-01;
  a16=(a02*a11);
  a16=(a10*a16);
  a17=(a07*a16);
  a15=(a15-a17);
  if (res[1]!=0) res[1][3]=a15;
  a15=(a08/a04);
  a17=(a15*a11);
  a12=(a12/a04);
  a17=(a17-a12);
  a17=(a01*a17);
  a12=(a08*a16);
  a17=(a17-a12);
  if (res[1]!=0) res[1][4]=a17;
  a17=(a09/a04);
  a11=(a17*a11);
  a13=(a13/a04);
  a11=(a11-a13);
  a11=(a01*a11);
  a16=(a09*a16);
  a11=(a11-a16);
  if (res[1]!=0) res[1][5]=a11;
  a11=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][6]=a11;
  a11=arg[1]? arg[1][10] : 0;
  if (res[1]!=0) res[1][7]=a11;
  a11=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][8]=a11;
  a11=arg[1]? arg[1][6] : 0;
  a16=(a03*a11);
  a13=arg[1]? arg[1][7] : 0;
  a12=(a05*a13);
  a16=(a16+a12);
  a12=arg[1]? arg[1][8] : 0;
  a18=(a06*a12);
  a16=(a16+a18);
  a16=(a16/a14);
  a18=(a00*a16);
  a11=(a11/a04);
  a18=(a18-a11);
  a18=(a01*a18);
  a11=(a02*a16);
  a11=(a10*a11);
  a19=(a07*a11);
  a18=(a18-a19);
  if (res[1]!=0) res[1][9]=a18;
  a18=(a15*a16);
  a13=(a13/a04);
  a18=(a18-a13);
  a18=(a01*a18);
  a13=(a08*a11);
  a18=(a18-a13);
  if (res[1]!=0) res[1][10]=a18;
  a16=(a17*a16);
  a12=(a12/a04);
  a16=(a16-a12);
  a16=(a01*a16);
  a11=(a09*a11);
  a16=(a16-a11);
  if (res[1]!=0) res[1][11]=a16;
  a16=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][12]=a16;
  a16=arg[1]? arg[1][16] : 0;
  if (res[1]!=0) res[1][13]=a16;
  a16=arg[1]? arg[1][17] : 0;
  if (res[1]!=0) res[1][14]=a16;
  a16=arg[1]? arg[1][12] : 0;
  a11=(a03*a16);
  a12=arg[1]? arg[1][13] : 0;
  a18=(a05*a12);
  a11=(a11+a18);
  a18=arg[1]? arg[1][14] : 0;
  a13=(a06*a18);
  a11=(a11+a13);
  a11=(a11/a14);
  a13=(a00*a11);
  a16=(a16/a04);
  a13=(a13-a16);
  a13=(a01*a13);
  a16=(a02*a11);
  a16=(a10*a16);
  a19=(a07*a16);
  a13=(a13-a19);
  if (res[1]!=0) res[1][15]=a13;
  a13=(a15*a11);
  a12=(a12/a04);
  a13=(a13-a12);
  a13=(a01*a13);
  a12=(a08*a16);
  a13=(a13-a12);
  if (res[1]!=0) res[1][16]=a13;
  a11=(a17*a11);
  a18=(a18/a04);
  a11=(a11-a18);
  a11=(a01*a11);
  a16=(a09*a16);
  a11=(a11-a16);
  if (res[1]!=0) res[1][17]=a11;
  a11=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][18]=a11;
  a11=arg[1]? arg[1][22] : 0;
  if (res[1]!=0) res[1][19]=a11;
  a11=arg[1]? arg[1][23] : 0;
  if (res[1]!=0) res[1][20]=a11;
  a11=arg[1]? arg[1][18] : 0;
  a16=(a03*a11);
  a18=arg[1]? arg[1][19] : 0;
  a13=(a05*a18);
  a16=(a16+a13);
  a13=arg[1]? arg[1][20] : 0;
  a12=(a06*a13);
  a16=(a16+a12);
  a16=(a16/a14);
  a12=(a00*a16);
  a11=(a11/a04);
  a12=(a12-a11);
  a12=(a01*a12);
  a11=(a02*a16);
  a11=(a10*a11);
  a19=(a07*a11);
  a12=(a12-a19);
  if (res[1]!=0) res[1][21]=a12;
  a12=(a15*a16);
  a18=(a18/a04);
  a12=(a12-a18);
  a12=(a01*a12);
  a18=(a08*a11);
  a12=(a12-a18);
  if (res[1]!=0) res[1][22]=a12;
  a16=(a17*a16);
  a13=(a13/a04);
  a16=(a16-a13);
  a16=(a01*a16);
  a11=(a09*a11);
  a16=(a16-a11);
  if (res[1]!=0) res[1][23]=a16;
  a16=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][24]=a16;
  a16=arg[1]? arg[1][28] : 0;
  if (res[1]!=0) res[1][25]=a16;
  a16=arg[1]? arg[1][29] : 0;
  if (res[1]!=0) res[1][26]=a16;
  a16=arg[1]? arg[1][24] : 0;
  a11=(a03*a16);
  a13=arg[1]? arg[1][25] : 0;
  a12=(a05*a13);
  a11=(a11+a12);
  a12=arg[1]? arg[1][26] : 0;
  a18=(a06*a12);
  a11=(a11+a18);
  a11=(a11/a14);
  a18=(a00*a11);
  a16=(a16/a04);
  a18=(a18-a16);
  a18=(a01*a18);
  a16=(a02*a11);
  a16=(a10*a16);
  a19=(a07*a16);
  a18=(a18-a19);
  if (res[1]!=0) res[1][27]=a18;
  a18=(a15*a11);
  a13=(a13/a04);
  a18=(a18-a13);
  a18=(a01*a18);
  a13=(a08*a16);
  a18=(a18-a13);
  if (res[1]!=0) res[1][28]=a18;
  a11=(a17*a11);
  a12=(a12/a04);
  a11=(a11-a12);
  a11=(a01*a11);
  a16=(a09*a16);
  a11=(a11-a16);
  if (res[1]!=0) res[1][29]=a11;
  a11=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][30]=a11;
  a11=arg[1]? arg[1][34] : 0;
  if (res[1]!=0) res[1][31]=a11;
  a11=arg[1]? arg[1][35] : 0;
  if (res[1]!=0) res[1][32]=a11;
  a11=arg[1]? arg[1][30] : 0;
  a16=(a03*a11);
  a12=arg[1]? arg[1][31] : 0;
  a18=(a05*a12);
  a16=(a16+a18);
  a18=arg[1]? arg[1][32] : 0;
  a13=(a06*a18);
  a16=(a16+a13);
  a16=(a16/a14);
  a13=(a00*a16);
  a11=(a11/a04);
  a13=(a13-a11);
  a13=(a01*a13);
  a11=(a02*a16);
  a11=(a10*a11);
  a19=(a07*a11);
  a13=(a13-a19);
  if (res[1]!=0) res[1][33]=a13;
  a13=(a15*a16);
  a12=(a12/a04);
  a13=(a13-a12);
  a13=(a01*a13);
  a12=(a08*a11);
  a13=(a13-a12);
  if (res[1]!=0) res[1][34]=a13;
  a16=(a17*a16);
  a18=(a18/a04);
  a16=(a16-a18);
  a16=(a01*a16);
  a11=(a09*a11);
  a16=(a16-a11);
  if (res[1]!=0) res[1][35]=a16;
  a16=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][0]=a16;
  a16=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][1]=a16;
  a16=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a16;
  a16=1.;
  a11=arg[2]? arg[2][0] : 0;
  a18=(a03*a11);
  a13=arg[2]? arg[2][1] : 0;
  a12=(a05*a13);
  a18=(a18+a12);
  a12=arg[2]? arg[2][2] : 0;
  a19=(a06*a12);
  a18=(a18+a19);
  a18=(a18/a14);
  a19=(a00*a18);
  a11=(a11/a04);
  a19=(a19-a11);
  a19=(a01*a19);
  a11=(a02*a18);
  a11=(a10*a11);
  a20=(a07*a11);
  a19=(a19-a20);
  a19=(a16+a19);
  if (res[2]!=0) res[2][3]=a19;
  a19=(a15*a18);
  a13=(a13/a04);
  a19=(a19-a13);
  a19=(a01*a19);
  a13=(a08*a11);
  a19=(a19-a13);
  if (res[2]!=0) res[2][4]=a19;
  a18=(a17*a18);
  a12=(a12/a04);
  a18=(a18-a12);
  a18=(a01*a18);
  a11=(a09*a11);
  a18=(a18-a11);
  if (res[2]!=0) res[2][5]=a18;
  a18=arg[2]? arg[2][9] : 0;
  if (res[2]!=0) res[2][6]=a18;
  a18=arg[2]? arg[2][10] : 0;
  if (res[2]!=0) res[2][7]=a18;
  a18=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][8]=a18;
  a18=arg[2]? arg[2][6] : 0;
  a11=(a03*a18);
  a12=arg[2]? arg[2][7] : 0;
  a19=(a05*a12);
  a11=(a11+a19);
  a19=arg[2]? arg[2][8] : 0;
  a13=(a06*a19);
  a11=(a11+a13);
  a11=(a11/a14);
  a13=(a00*a11);
  a18=(a18/a04);
  a13=(a13-a18);
  a13=(a01*a13);
  a18=(a02*a11);
  a18=(a10*a18);
  a20=(a07*a18);
  a13=(a13-a20);
  if (res[2]!=0) res[2][9]=a13;
  a13=(a15*a11);
  a12=(a12/a04);
  a13=(a13-a12);
  a13=(a01*a13);
  a12=(a08*a18);
  a13=(a13-a12);
  a13=(a16+a13);
  if (res[2]!=0) res[2][10]=a13;
  a11=(a17*a11);
  a19=(a19/a04);
  a11=(a11-a19);
  a11=(a01*a11);
  a18=(a09*a18);
  a11=(a11-a18);
  if (res[2]!=0) res[2][11]=a11;
  a11=arg[2]? arg[2][15] : 0;
  if (res[2]!=0) res[2][12]=a11;
  a11=arg[2]? arg[2][16] : 0;
  if (res[2]!=0) res[2][13]=a11;
  a11=arg[2]? arg[2][17] : 0;
  if (res[2]!=0) res[2][14]=a11;
  a11=arg[2]? arg[2][12] : 0;
  a03=(a03*a11);
  a18=arg[2]? arg[2][13] : 0;
  a05=(a05*a18);
  a03=(a03+a05);
  a05=arg[2]? arg[2][14] : 0;
  a06=(a06*a05);
  a03=(a03+a06);
  a03=(a03/a14);
  a00=(a00*a03);
  a11=(a11/a04);
  a00=(a00-a11);
  a00=(a01*a00);
  a02=(a02*a03);
  a10=(a10*a02);
  a07=(a07*a10);
  a00=(a00-a07);
  if (res[2]!=0) res[2][15]=a00;
  a15=(a15*a03);
  a18=(a18/a04);
  a15=(a15-a18);
  a15=(a01*a15);
  a08=(a08*a10);
  a15=(a15-a08);
  if (res[2]!=0) res[2][16]=a15;
  a17=(a17*a03);
  a05=(a05/a04);
  a17=(a17-a05);
  a01=(a01*a17);
  a09=(a09*a10);
  a01=(a01-a09);
  a16=(a16+a01);
  if (res[2]!=0) res[2][17]=a16;
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int uav_tethered_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int uav_tethered_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real uav_tethered_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* uav_tethered_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* uav_tethered_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* uav_tethered_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* uav_tethered_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
