/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) uav_tethered_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {8, 8, 1};
static const casadi_int casadi_s2[3] = {8, 3, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};
static const casadi_int casadi_s4[3] = {1, 1, 1};

/* uav_tethered_expl_vde_forw:(i0[8],i1[8x8],i2[8x3],i3[3],i4)->(o0[8],o1[8x8],o2[8x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[3]? arg[3][2] : 0;
  a01=arg[4]? arg[4][0] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][7] : 0;
  a04=sin(a03);
  a05=(a02*a04);
  a06=arg[0]? arg[0][6] : 0;
  a07=cos(a06);
  a08=(a05*a07);
  a01=sin(a01);
  a06=sin(a06);
  a09=(a01*a06);
  a08=(a08+a09);
  a09=(a00*a08);
  if (res[0]!=0) res[0][3]=a09;
  a09=(a01*a04);
  a10=(a09*a07);
  a11=(a02*a06);
  a10=(a10-a11);
  a11=(a00*a10);
  if (res[0]!=0) res[0][4]=a11;
  a03=cos(a03);
  a11=(a03*a07);
  a12=(a00*a11);
  a13=-9.8100000000000005e+00;
  a12=(a12+a13);
  if (res[0]!=0) res[0][5]=a12;
  a12=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][6]=a12;
  a12=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][7]=a12;
  a12=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][0]=a12;
  a12=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][1]=a12;
  a12=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a12;
  a12=arg[1]? arg[1][7] : 0;
  a13=(a03*a12);
  a14=(a02*a13);
  a14=(a07*a14);
  a15=arg[1]? arg[1][6] : 0;
  a16=(a06*a15);
  a17=(a05*a16);
  a14=(a14-a17);
  a15=(a07*a15);
  a17=(a01*a15);
  a14=(a14+a17);
  a14=(a00*a14);
  if (res[1]!=0) res[1][3]=a14;
  a13=(a01*a13);
  a13=(a07*a13);
  a14=(a09*a16);
  a13=(a13-a14);
  a15=(a02*a15);
  a13=(a13-a15);
  a13=(a00*a13);
  if (res[1]!=0) res[1][4]=a13;
  a12=(a04*a12);
  a12=(a07*a12);
  a16=(a03*a16);
  a12=(a12+a16);
  a12=(a00*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][5]=a12;
  a12=0.;
  if (res[1]!=0) res[1][6]=a12;
  if (res[1]!=0) res[1][7]=a12;
  a16=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][8]=a16;
  a16=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][9]=a16;
  a16=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][10]=a16;
  a16=arg[1]? arg[1][15] : 0;
  a13=(a03*a16);
  a15=(a02*a13);
  a15=(a07*a15);
  a14=arg[1]? arg[1][14] : 0;
  a17=(a06*a14);
  a18=(a05*a17);
  a15=(a15-a18);
  a14=(a07*a14);
  a18=(a01*a14);
  a15=(a15+a18);
  a15=(a00*a15);
  if (res[1]!=0) res[1][11]=a15;
  a13=(a01*a13);
  a13=(a07*a13);
  a15=(a09*a17);
  a13=(a13-a15);
  a14=(a02*a14);
  a13=(a13-a14);
  a13=(a00*a13);
  if (res[1]!=0) res[1][12]=a13;
  a16=(a04*a16);
  a16=(a07*a16);
  a17=(a03*a17);
  a16=(a16+a17);
  a16=(a00*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][13]=a16;
  if (res[1]!=0) res[1][14]=a12;
  if (res[1]!=0) res[1][15]=a12;
  a16=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][16]=a16;
  a16=arg[1]? arg[1][20] : 0;
  if (res[1]!=0) res[1][17]=a16;
  a16=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][18]=a16;
  a16=arg[1]? arg[1][23] : 0;
  a17=(a03*a16);
  a13=(a02*a17);
  a13=(a07*a13);
  a14=arg[1]? arg[1][22] : 0;
  a15=(a06*a14);
  a18=(a05*a15);
  a13=(a13-a18);
  a14=(a07*a14);
  a18=(a01*a14);
  a13=(a13+a18);
  a13=(a00*a13);
  if (res[1]!=0) res[1][19]=a13;
  a17=(a01*a17);
  a17=(a07*a17);
  a13=(a09*a15);
  a17=(a17-a13);
  a14=(a02*a14);
  a17=(a17-a14);
  a17=(a00*a17);
  if (res[1]!=0) res[1][20]=a17;
  a16=(a04*a16);
  a16=(a07*a16);
  a15=(a03*a15);
  a16=(a16+a15);
  a16=(a00*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][21]=a16;
  if (res[1]!=0) res[1][22]=a12;
  if (res[1]!=0) res[1][23]=a12;
  a16=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][24]=a16;
  a16=arg[1]? arg[1][28] : 0;
  if (res[1]!=0) res[1][25]=a16;
  a16=arg[1]? arg[1][29] : 0;
  if (res[1]!=0) res[1][26]=a16;
  a16=arg[1]? arg[1][31] : 0;
  a15=(a03*a16);
  a17=(a02*a15);
  a17=(a07*a17);
  a14=arg[1]? arg[1][30] : 0;
  a13=(a06*a14);
  a18=(a05*a13);
  a17=(a17-a18);
  a14=(a07*a14);
  a18=(a01*a14);
  a17=(a17+a18);
  a17=(a00*a17);
  if (res[1]!=0) res[1][27]=a17;
  a15=(a01*a15);
  a15=(a07*a15);
  a17=(a09*a13);
  a15=(a15-a17);
  a14=(a02*a14);
  a15=(a15-a14);
  a15=(a00*a15);
  if (res[1]!=0) res[1][28]=a15;
  a16=(a04*a16);
  a16=(a07*a16);
  a13=(a03*a13);
  a16=(a16+a13);
  a16=(a00*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][29]=a16;
  if (res[1]!=0) res[1][30]=a12;
  if (res[1]!=0) res[1][31]=a12;
  a16=arg[1]? arg[1][35] : 0;
  if (res[1]!=0) res[1][32]=a16;
  a16=arg[1]? arg[1][36] : 0;
  if (res[1]!=0) res[1][33]=a16;
  a16=arg[1]? arg[1][37] : 0;
  if (res[1]!=0) res[1][34]=a16;
  a16=arg[1]? arg[1][39] : 0;
  a13=(a03*a16);
  a15=(a02*a13);
  a15=(a07*a15);
  a14=arg[1]? arg[1][38] : 0;
  a17=(a06*a14);
  a18=(a05*a17);
  a15=(a15-a18);
  a14=(a07*a14);
  a18=(a01*a14);
  a15=(a15+a18);
  a15=(a00*a15);
  if (res[1]!=0) res[1][35]=a15;
  a13=(a01*a13);
  a13=(a07*a13);
  a15=(a09*a17);
  a13=(a13-a15);
  a14=(a02*a14);
  a13=(a13-a14);
  a13=(a00*a13);
  if (res[1]!=0) res[1][36]=a13;
  a16=(a04*a16);
  a16=(a07*a16);
  a17=(a03*a17);
  a16=(a16+a17);
  a16=(a00*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][37]=a16;
  if (res[1]!=0) res[1][38]=a12;
  if (res[1]!=0) res[1][39]=a12;
  a16=arg[1]? arg[1][43] : 0;
  if (res[1]!=0) res[1][40]=a16;
  a16=arg[1]? arg[1][44] : 0;
  if (res[1]!=0) res[1][41]=a16;
  a16=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][42]=a16;
  a16=arg[1]? arg[1][47] : 0;
  a17=(a03*a16);
  a13=(a02*a17);
  a13=(a07*a13);
  a14=arg[1]? arg[1][46] : 0;
  a15=(a06*a14);
  a18=(a05*a15);
  a13=(a13-a18);
  a14=(a07*a14);
  a18=(a01*a14);
  a13=(a13+a18);
  a13=(a00*a13);
  if (res[1]!=0) res[1][43]=a13;
  a17=(a01*a17);
  a17=(a07*a17);
  a13=(a09*a15);
  a17=(a17-a13);
  a14=(a02*a14);
  a17=(a17-a14);
  a17=(a00*a17);
  if (res[1]!=0) res[1][44]=a17;
  a16=(a04*a16);
  a16=(a07*a16);
  a15=(a03*a15);
  a16=(a16+a15);
  a16=(a00*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][45]=a16;
  if (res[1]!=0) res[1][46]=a12;
  if (res[1]!=0) res[1][47]=a12;
  a16=arg[1]? arg[1][51] : 0;
  if (res[1]!=0) res[1][48]=a16;
  a16=arg[1]? arg[1][52] : 0;
  if (res[1]!=0) res[1][49]=a16;
  a16=arg[1]? arg[1][53] : 0;
  if (res[1]!=0) res[1][50]=a16;
  a16=arg[1]? arg[1][55] : 0;
  a15=(a03*a16);
  a17=(a02*a15);
  a17=(a07*a17);
  a14=arg[1]? arg[1][54] : 0;
  a13=(a06*a14);
  a18=(a05*a13);
  a17=(a17-a18);
  a14=(a07*a14);
  a18=(a01*a14);
  a17=(a17+a18);
  a17=(a00*a17);
  if (res[1]!=0) res[1][51]=a17;
  a15=(a01*a15);
  a15=(a07*a15);
  a17=(a09*a13);
  a15=(a15-a17);
  a14=(a02*a14);
  a15=(a15-a14);
  a15=(a00*a15);
  if (res[1]!=0) res[1][52]=a15;
  a16=(a04*a16);
  a16=(a07*a16);
  a13=(a03*a13);
  a16=(a16+a13);
  a16=(a00*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][53]=a16;
  if (res[1]!=0) res[1][54]=a12;
  if (res[1]!=0) res[1][55]=a12;
  a16=arg[1]? arg[1][59] : 0;
  if (res[1]!=0) res[1][56]=a16;
  a16=arg[1]? arg[1][60] : 0;
  if (res[1]!=0) res[1][57]=a16;
  a16=arg[1]? arg[1][61] : 0;
  if (res[1]!=0) res[1][58]=a16;
  a16=arg[1]? arg[1][63] : 0;
  a13=(a03*a16);
  a15=(a02*a13);
  a15=(a07*a15);
  a14=arg[1]? arg[1][62] : 0;
  a17=(a06*a14);
  a18=(a05*a17);
  a15=(a15-a18);
  a14=(a07*a14);
  a18=(a01*a14);
  a15=(a15+a18);
  a15=(a00*a15);
  if (res[1]!=0) res[1][59]=a15;
  a13=(a01*a13);
  a13=(a07*a13);
  a15=(a09*a17);
  a13=(a13-a15);
  a14=(a02*a14);
  a13=(a13-a14);
  a13=(a00*a13);
  if (res[1]!=0) res[1][60]=a13;
  a16=(a04*a16);
  a16=(a07*a16);
  a17=(a03*a17);
  a16=(a16+a17);
  a16=(a00*a16);
  a16=(-a16);
  if (res[1]!=0) res[1][61]=a16;
  if (res[1]!=0) res[1][62]=a12;
  if (res[1]!=0) res[1][63]=a12;
  a16=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][0]=a16;
  a16=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][1]=a16;
  a16=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a16;
  a16=arg[2]? arg[2][7] : 0;
  a17=(a03*a16);
  a13=(a02*a17);
  a13=(a07*a13);
  a14=arg[2]? arg[2][6] : 0;
  a15=(a06*a14);
  a18=(a05*a15);
  a13=(a13-a18);
  a14=(a07*a14);
  a18=(a01*a14);
  a13=(a13+a18);
  a13=(a00*a13);
  if (res[2]!=0) res[2][3]=a13;
  a17=(a01*a17);
  a17=(a07*a17);
  a13=(a09*a15);
  a17=(a17-a13);
  a14=(a02*a14);
  a17=(a17-a14);
  a17=(a00*a17);
  if (res[2]!=0) res[2][4]=a17;
  a16=(a04*a16);
  a16=(a07*a16);
  a15=(a03*a15);
  a16=(a16+a15);
  a16=(a00*a16);
  a16=(-a16);
  if (res[2]!=0) res[2][5]=a16;
  a16=1.;
  if (res[2]!=0) res[2][6]=a16;
  if (res[2]!=0) res[2][7]=a12;
  a15=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][8]=a15;
  a15=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][9]=a15;
  a15=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][10]=a15;
  a15=arg[2]? arg[2][15] : 0;
  a17=(a03*a15);
  a14=(a02*a17);
  a14=(a07*a14);
  a13=arg[2]? arg[2][14] : 0;
  a18=(a06*a13);
  a19=(a05*a18);
  a14=(a14-a19);
  a13=(a07*a13);
  a19=(a01*a13);
  a14=(a14+a19);
  a14=(a00*a14);
  if (res[2]!=0) res[2][11]=a14;
  a17=(a01*a17);
  a17=(a07*a17);
  a14=(a09*a18);
  a17=(a17-a14);
  a13=(a02*a13);
  a17=(a17-a13);
  a17=(a00*a17);
  if (res[2]!=0) res[2][12]=a17;
  a15=(a04*a15);
  a15=(a07*a15);
  a18=(a03*a18);
  a15=(a15+a18);
  a15=(a00*a15);
  a15=(-a15);
  if (res[2]!=0) res[2][13]=a15;
  if (res[2]!=0) res[2][14]=a12;
  if (res[2]!=0) res[2][15]=a16;
  a16=arg[2]? arg[2][19] : 0;
  if (res[2]!=0) res[2][16]=a16;
  a16=arg[2]? arg[2][20] : 0;
  if (res[2]!=0) res[2][17]=a16;
  a16=arg[2]? arg[2][21] : 0;
  if (res[2]!=0) res[2][18]=a16;
  a16=arg[2]? arg[2][23] : 0;
  a15=(a03*a16);
  a18=(a02*a15);
  a18=(a07*a18);
  a17=arg[2]? arg[2][22] : 0;
  a06=(a06*a17);
  a05=(a05*a06);
  a18=(a18-a05);
  a17=(a07*a17);
  a05=(a01*a17);
  a18=(a18+a05);
  a18=(a00*a18);
  a08=(a08+a18);
  if (res[2]!=0) res[2][19]=a08;
  a01=(a01*a15);
  a01=(a07*a01);
  a09=(a09*a06);
  a01=(a01-a09);
  a02=(a02*a17);
  a01=(a01-a02);
  a01=(a00*a01);
  a10=(a10+a01);
  if (res[2]!=0) res[2][20]=a10;
  a04=(a04*a16);
  a07=(a07*a04);
  a03=(a03*a06);
  a07=(a07+a03);
  a00=(a00*a07);
  a11=(a11-a00);
  if (res[2]!=0) res[2][21]=a11;
  if (res[2]!=0) res[2][22]=a12;
  if (res[2]!=0) res[2][23]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int uav_tethered_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int uav_tethered_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real uav_tethered_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* uav_tethered_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* uav_tethered_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* uav_tethered_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* uav_tethered_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
