/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) uav_tethered_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fmax CASADI_PREFIX(fmax)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_fmax(casadi_real x, casadi_real y) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>y ? x : y;
#else
  return fmax(x, y);
#endif
}

static const casadi_int casadi_s0[3] = {8, 1, 1};
static const casadi_int casadi_s1[3] = {8, 8, 1};
static const casadi_int casadi_s2[3] = {8, 3, 1};
static const casadi_int casadi_s3[3] = {3, 1, 1};

/* uav_tethered_expl_vde_forw:(i0[8],i1[8x8],i2[8x3],i3[3],i4[8])->(o0[8],o1[8x8],o2[8x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30;
  a00=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a02=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a02;
  a03=arg[3]? arg[3][2] : 0;
  a04=arg[4]? arg[4][6] : 0;
  a05=cos(a04);
  a06=arg[0]? arg[0][7] : 0;
  a07=sin(a06);
  a08=(a05*a07);
  a09=arg[0]? arg[0][6] : 0;
  a10=cos(a09);
  a11=(a08*a10);
  a04=sin(a04);
  a12=sin(a09);
  a13=(a04*a12);
  a11=(a11+a13);
  a13=(a03*a11);
  a14=-1.4999999999999999e-01;
  a00=(a14*a00);
  a13=(a13+a00);
  if (res[0]!=0) res[0][3]=a13;
  a13=(a04*a07);
  a00=(a13*a10);
  a15=(a05*a12);
  a00=(a00-a15);
  a15=(a03*a00);
  a01=(a14*a01);
  a15=(a15+a01);
  if (res[0]!=0) res[0][4]=a15;
  a15=cos(a06);
  a01=(a15*a10);
  a16=(a03*a01);
  a17=-9.8100000000000005e+00;
  a16=(a16+a17);
  a17=arg[4]? arg[4][3] : 0;
  a18=arg[4]? arg[4][4] : 0;
  a19=arg[4]? arg[4][0] : 0;
  a20=arg[0]? arg[0][0] : 0;
  a19=(a19-a20);
  a20=casadi_sq(a19);
  a21=arg[4]? arg[4][1] : 0;
  a22=arg[0]? arg[0][1] : 0;
  a21=(a21-a22);
  a22=casadi_sq(a21);
  a20=(a20+a22);
  a22=arg[4]? arg[4][2] : 0;
  a23=arg[0]? arg[0][2] : 0;
  a22=(a22-a23);
  a23=casadi_sq(a22);
  a20=(a20+a23);
  a23=arg[4]? arg[4][5] : 0;
  a23=casadi_sq(a23);
  a20=(a20+a23);
  a20=sqrt(a20);
  a23=(a18*a20);
  a17=(a17+a23);
  a23=2.0600000000000001e+00;
  a17=(a17/a23);
  a16=(a16-a17);
  a02=(a14*a02);
  a16=(a16+a02);
  if (res[0]!=0) res[0][5]=a16;
  a16=arg[3]? arg[3][0] : 0;
  a16=(a16-a09);
  a09=arg[4]? arg[4][7] : 0;
  a02=1.0000000000000000e-02;
  a09=casadi_fmax(a09,a02);
  a16=(a16/a09);
  if (res[0]!=0) res[0][6]=a16;
  a16=arg[3]? arg[3][1] : 0;
  a16=(a16-a06);
  a16=(a16/a09);
  if (res[0]!=0) res[0][7]=a16;
  a16=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][0]=a16;
  a06=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][1]=a06;
  a02=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][2]=a02;
  a17=arg[1]? arg[1][7] : 0;
  a23=(a15*a17);
  a24=(a05*a23);
  a24=(a10*a24);
  a25=arg[1]? arg[1][6] : 0;
  a26=(a12*a25);
  a27=(a08*a26);
  a24=(a24-a27);
  a27=(a10*a25);
  a28=(a04*a27);
  a24=(a24+a28);
  a24=(a03*a24);
  a16=(a14*a16);
  a24=(a24+a16);
  if (res[1]!=0) res[1][3]=a24;
  a23=(a04*a23);
  a23=(a10*a23);
  a24=(a13*a26);
  a23=(a23-a24);
  a27=(a05*a27);
  a23=(a23-a27);
  a23=(a03*a23);
  a06=(a14*a06);
  a23=(a23+a06);
  if (res[1]!=0) res[1][4]=a23;
  a23=4.8543689320388350e-01;
  a19=(a19+a19);
  a06=arg[1]? arg[1][0] : 0;
  a06=(a19*a06);
  a21=(a21+a21);
  a27=arg[1]? arg[1][1] : 0;
  a27=(a21*a27);
  a06=(a06+a27);
  a22=(a22+a22);
  a27=arg[1]? arg[1][2] : 0;
  a27=(a22*a27);
  a06=(a06+a27);
  a20=(a20+a20);
  a06=(a06/a20);
  a06=(a18*a06);
  a06=(a23*a06);
  a27=(a07*a17);
  a27=(a10*a27);
  a26=(a15*a26);
  a27=(a27+a26);
  a27=(a03*a27);
  a06=(a06-a27);
  a02=(a14*a02);
  a06=(a06+a02);
  if (res[1]!=0) res[1][5]=a06;
  a25=(a25/a09);
  a25=(-a25);
  if (res[1]!=0) res[1][6]=a25;
  a17=(a17/a09);
  a17=(-a17);
  if (res[1]!=0) res[1][7]=a17;
  a17=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][8]=a17;
  a25=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][9]=a25;
  a06=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][10]=a06;
  a02=arg[1]? arg[1][15] : 0;
  a27=(a15*a02);
  a26=(a05*a27);
  a26=(a10*a26);
  a24=arg[1]? arg[1][14] : 0;
  a16=(a12*a24);
  a28=(a08*a16);
  a26=(a26-a28);
  a28=(a10*a24);
  a29=(a04*a28);
  a26=(a26+a29);
  a26=(a03*a26);
  a17=(a14*a17);
  a26=(a26+a17);
  if (res[1]!=0) res[1][11]=a26;
  a27=(a04*a27);
  a27=(a10*a27);
  a26=(a13*a16);
  a27=(a27-a26);
  a28=(a05*a28);
  a27=(a27-a28);
  a27=(a03*a27);
  a25=(a14*a25);
  a27=(a27+a25);
  if (res[1]!=0) res[1][12]=a27;
  a27=arg[1]? arg[1][8] : 0;
  a27=(a19*a27);
  a25=arg[1]? arg[1][9] : 0;
  a25=(a21*a25);
  a27=(a27+a25);
  a25=arg[1]? arg[1][10] : 0;
  a25=(a22*a25);
  a27=(a27+a25);
  a27=(a27/a20);
  a27=(a18*a27);
  a27=(a23*a27);
  a25=(a07*a02);
  a25=(a10*a25);
  a16=(a15*a16);
  a25=(a25+a16);
  a25=(a03*a25);
  a27=(a27-a25);
  a06=(a14*a06);
  a27=(a27+a06);
  if (res[1]!=0) res[1][13]=a27;
  a24=(a24/a09);
  a24=(-a24);
  if (res[1]!=0) res[1][14]=a24;
  a02=(a02/a09);
  a02=(-a02);
  if (res[1]!=0) res[1][15]=a02;
  a02=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][16]=a02;
  a24=arg[1]? arg[1][20] : 0;
  if (res[1]!=0) res[1][17]=a24;
  a27=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][18]=a27;
  a06=arg[1]? arg[1][23] : 0;
  a25=(a15*a06);
  a16=(a05*a25);
  a16=(a10*a16);
  a28=arg[1]? arg[1][22] : 0;
  a26=(a12*a28);
  a17=(a08*a26);
  a16=(a16-a17);
  a17=(a10*a28);
  a29=(a04*a17);
  a16=(a16+a29);
  a16=(a03*a16);
  a02=(a14*a02);
  a16=(a16+a02);
  if (res[1]!=0) res[1][19]=a16;
  a25=(a04*a25);
  a25=(a10*a25);
  a16=(a13*a26);
  a25=(a25-a16);
  a17=(a05*a17);
  a25=(a25-a17);
  a25=(a03*a25);
  a24=(a14*a24);
  a25=(a25+a24);
  if (res[1]!=0) res[1][20]=a25;
  a25=arg[1]? arg[1][16] : 0;
  a25=(a19*a25);
  a24=arg[1]? arg[1][17] : 0;
  a24=(a21*a24);
  a25=(a25+a24);
  a24=arg[1]? arg[1][18] : 0;
  a24=(a22*a24);
  a25=(a25+a24);
  a25=(a25/a20);
  a25=(a18*a25);
  a25=(a23*a25);
  a24=(a07*a06);
  a24=(a10*a24);
  a26=(a15*a26);
  a24=(a24+a26);
  a24=(a03*a24);
  a25=(a25-a24);
  a27=(a14*a27);
  a25=(a25+a27);
  if (res[1]!=0) res[1][21]=a25;
  a28=(a28/a09);
  a28=(-a28);
  if (res[1]!=0) res[1][22]=a28;
  a06=(a06/a09);
  a06=(-a06);
  if (res[1]!=0) res[1][23]=a06;
  a06=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][24]=a06;
  a28=arg[1]? arg[1][28] : 0;
  if (res[1]!=0) res[1][25]=a28;
  a25=arg[1]? arg[1][29] : 0;
  if (res[1]!=0) res[1][26]=a25;
  a27=arg[1]? arg[1][31] : 0;
  a24=(a15*a27);
  a26=(a05*a24);
  a26=(a10*a26);
  a17=arg[1]? arg[1][30] : 0;
  a16=(a12*a17);
  a02=(a08*a16);
  a26=(a26-a02);
  a02=(a10*a17);
  a29=(a04*a02);
  a26=(a26+a29);
  a26=(a03*a26);
  a06=(a14*a06);
  a26=(a26+a06);
  if (res[1]!=0) res[1][27]=a26;
  a24=(a04*a24);
  a24=(a10*a24);
  a26=(a13*a16);
  a24=(a24-a26);
  a02=(a05*a02);
  a24=(a24-a02);
  a24=(a03*a24);
  a28=(a14*a28);
  a24=(a24+a28);
  if (res[1]!=0) res[1][28]=a24;
  a24=arg[1]? arg[1][24] : 0;
  a24=(a19*a24);
  a28=arg[1]? arg[1][25] : 0;
  a28=(a21*a28);
  a24=(a24+a28);
  a28=arg[1]? arg[1][26] : 0;
  a28=(a22*a28);
  a24=(a24+a28);
  a24=(a24/a20);
  a24=(a18*a24);
  a24=(a23*a24);
  a28=(a07*a27);
  a28=(a10*a28);
  a16=(a15*a16);
  a28=(a28+a16);
  a28=(a03*a28);
  a24=(a24-a28);
  a25=(a14*a25);
  a24=(a24+a25);
  if (res[1]!=0) res[1][29]=a24;
  a17=(a17/a09);
  a17=(-a17);
  if (res[1]!=0) res[1][30]=a17;
  a27=(a27/a09);
  a27=(-a27);
  if (res[1]!=0) res[1][31]=a27;
  a27=arg[1]? arg[1][35] : 0;
  if (res[1]!=0) res[1][32]=a27;
  a17=arg[1]? arg[1][36] : 0;
  if (res[1]!=0) res[1][33]=a17;
  a24=arg[1]? arg[1][37] : 0;
  if (res[1]!=0) res[1][34]=a24;
  a25=arg[1]? arg[1][39] : 0;
  a28=(a15*a25);
  a16=(a05*a28);
  a16=(a10*a16);
  a02=arg[1]? arg[1][38] : 0;
  a26=(a12*a02);
  a06=(a08*a26);
  a16=(a16-a06);
  a06=(a10*a02);
  a29=(a04*a06);
  a16=(a16+a29);
  a16=(a03*a16);
  a27=(a14*a27);
  a16=(a16+a27);
  if (res[1]!=0) res[1][35]=a16;
  a28=(a04*a28);
  a28=(a10*a28);
  a16=(a13*a26);
  a28=(a28-a16);
  a06=(a05*a06);
  a28=(a28-a06);
  a28=(a03*a28);
  a17=(a14*a17);
  a28=(a28+a17);
  if (res[1]!=0) res[1][36]=a28;
  a28=arg[1]? arg[1][32] : 0;
  a28=(a19*a28);
  a17=arg[1]? arg[1][33] : 0;
  a17=(a21*a17);
  a28=(a28+a17);
  a17=arg[1]? arg[1][34] : 0;
  a17=(a22*a17);
  a28=(a28+a17);
  a28=(a28/a20);
  a28=(a18*a28);
  a28=(a23*a28);
  a17=(a07*a25);
  a17=(a10*a17);
  a26=(a15*a26);
  a17=(a17+a26);
  a17=(a03*a17);
  a28=(a28-a17);
  a24=(a14*a24);
  a28=(a28+a24);
  if (res[1]!=0) res[1][37]=a28;
  a02=(a02/a09);
  a02=(-a02);
  if (res[1]!=0) res[1][38]=a02;
  a25=(a25/a09);
  a25=(-a25);
  if (res[1]!=0) res[1][39]=a25;
  a25=arg[1]? arg[1][43] : 0;
  if (res[1]!=0) res[1][40]=a25;
  a02=arg[1]? arg[1][44] : 0;
  if (res[1]!=0) res[1][41]=a02;
  a28=arg[1]? arg[1][45] : 0;
  if (res[1]!=0) res[1][42]=a28;
  a24=arg[1]? arg[1][47] : 0;
  a17=(a15*a24);
  a26=(a05*a17);
  a26=(a10*a26);
  a06=arg[1]? arg[1][46] : 0;
  a16=(a12*a06);
  a27=(a08*a16);
  a26=(a26-a27);
  a27=(a10*a06);
  a29=(a04*a27);
  a26=(a26+a29);
  a26=(a03*a26);
  a25=(a14*a25);
  a26=(a26+a25);
  if (res[1]!=0) res[1][43]=a26;
  a17=(a04*a17);
  a17=(a10*a17);
  a26=(a13*a16);
  a17=(a17-a26);
  a27=(a05*a27);
  a17=(a17-a27);
  a17=(a03*a17);
  a02=(a14*a02);
  a17=(a17+a02);
  if (res[1]!=0) res[1][44]=a17;
  a17=arg[1]? arg[1][40] : 0;
  a17=(a19*a17);
  a02=arg[1]? arg[1][41] : 0;
  a02=(a21*a02);
  a17=(a17+a02);
  a02=arg[1]? arg[1][42] : 0;
  a02=(a22*a02);
  a17=(a17+a02);
  a17=(a17/a20);
  a17=(a18*a17);
  a17=(a23*a17);
  a02=(a07*a24);
  a02=(a10*a02);
  a16=(a15*a16);
  a02=(a02+a16);
  a02=(a03*a02);
  a17=(a17-a02);
  a28=(a14*a28);
  a17=(a17+a28);
  if (res[1]!=0) res[1][45]=a17;
  a06=(a06/a09);
  a06=(-a06);
  if (res[1]!=0) res[1][46]=a06;
  a24=(a24/a09);
  a24=(-a24);
  if (res[1]!=0) res[1][47]=a24;
  a24=arg[1]? arg[1][51] : 0;
  if (res[1]!=0) res[1][48]=a24;
  a06=arg[1]? arg[1][52] : 0;
  if (res[1]!=0) res[1][49]=a06;
  a17=arg[1]? arg[1][53] : 0;
  if (res[1]!=0) res[1][50]=a17;
  a28=arg[1]? arg[1][55] : 0;
  a02=(a15*a28);
  a16=(a05*a02);
  a16=(a10*a16);
  a27=arg[1]? arg[1][54] : 0;
  a26=(a12*a27);
  a25=(a08*a26);
  a16=(a16-a25);
  a25=(a10*a27);
  a29=(a04*a25);
  a16=(a16+a29);
  a16=(a03*a16);
  a24=(a14*a24);
  a16=(a16+a24);
  if (res[1]!=0) res[1][51]=a16;
  a02=(a04*a02);
  a02=(a10*a02);
  a16=(a13*a26);
  a02=(a02-a16);
  a25=(a05*a25);
  a02=(a02-a25);
  a02=(a03*a02);
  a06=(a14*a06);
  a02=(a02+a06);
  if (res[1]!=0) res[1][52]=a02;
  a02=arg[1]? arg[1][48] : 0;
  a02=(a19*a02);
  a06=arg[1]? arg[1][49] : 0;
  a06=(a21*a06);
  a02=(a02+a06);
  a06=arg[1]? arg[1][50] : 0;
  a06=(a22*a06);
  a02=(a02+a06);
  a02=(a02/a20);
  a02=(a18*a02);
  a02=(a23*a02);
  a06=(a07*a28);
  a06=(a10*a06);
  a26=(a15*a26);
  a06=(a06+a26);
  a06=(a03*a06);
  a02=(a02-a06);
  a17=(a14*a17);
  a02=(a02+a17);
  if (res[1]!=0) res[1][53]=a02;
  a27=(a27/a09);
  a27=(-a27);
  if (res[1]!=0) res[1][54]=a27;
  a28=(a28/a09);
  a28=(-a28);
  if (res[1]!=0) res[1][55]=a28;
  a28=arg[1]? arg[1][59] : 0;
  if (res[1]!=0) res[1][56]=a28;
  a27=arg[1]? arg[1][60] : 0;
  if (res[1]!=0) res[1][57]=a27;
  a02=arg[1]? arg[1][61] : 0;
  if (res[1]!=0) res[1][58]=a02;
  a17=arg[1]? arg[1][63] : 0;
  a06=(a15*a17);
  a26=(a05*a06);
  a26=(a10*a26);
  a25=arg[1]? arg[1][62] : 0;
  a16=(a12*a25);
  a24=(a08*a16);
  a26=(a26-a24);
  a24=(a10*a25);
  a29=(a04*a24);
  a26=(a26+a29);
  a26=(a03*a26);
  a28=(a14*a28);
  a26=(a26+a28);
  if (res[1]!=0) res[1][59]=a26;
  a06=(a04*a06);
  a06=(a10*a06);
  a26=(a13*a16);
  a06=(a06-a26);
  a24=(a05*a24);
  a06=(a06-a24);
  a06=(a03*a06);
  a27=(a14*a27);
  a06=(a06+a27);
  if (res[1]!=0) res[1][60]=a06;
  a06=arg[1]? arg[1][56] : 0;
  a06=(a19*a06);
  a27=arg[1]? arg[1][57] : 0;
  a27=(a21*a27);
  a06=(a06+a27);
  a27=arg[1]? arg[1][58] : 0;
  a27=(a22*a27);
  a06=(a06+a27);
  a06=(a06/a20);
  a06=(a18*a06);
  a06=(a23*a06);
  a27=(a07*a17);
  a27=(a10*a27);
  a16=(a15*a16);
  a27=(a27+a16);
  a27=(a03*a27);
  a06=(a06-a27);
  a02=(a14*a02);
  a06=(a06+a02);
  if (res[1]!=0) res[1][61]=a06;
  a25=(a25/a09);
  a25=(-a25);
  if (res[1]!=0) res[1][62]=a25;
  a17=(a17/a09);
  a17=(-a17);
  if (res[1]!=0) res[1][63]=a17;
  a17=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][0]=a17;
  a25=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][1]=a25;
  a06=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][2]=a06;
  a02=arg[2]? arg[2][7] : 0;
  a27=(a15*a02);
  a16=(a05*a27);
  a16=(a10*a16);
  a24=arg[2]? arg[2][6] : 0;
  a26=(a12*a24);
  a28=(a08*a26);
  a16=(a16-a28);
  a28=(a10*a24);
  a29=(a04*a28);
  a16=(a16+a29);
  a16=(a03*a16);
  a17=(a14*a17);
  a16=(a16+a17);
  if (res[2]!=0) res[2][3]=a16;
  a27=(a04*a27);
  a27=(a10*a27);
  a16=(a13*a26);
  a27=(a27-a16);
  a28=(a05*a28);
  a27=(a27-a28);
  a27=(a03*a27);
  a25=(a14*a25);
  a27=(a27+a25);
  if (res[2]!=0) res[2][4]=a27;
  a27=arg[2]? arg[2][0] : 0;
  a27=(a19*a27);
  a25=arg[2]? arg[2][1] : 0;
  a25=(a21*a25);
  a27=(a27+a25);
  a25=arg[2]? arg[2][2] : 0;
  a25=(a22*a25);
  a27=(a27+a25);
  a27=(a27/a20);
  a27=(a18*a27);
  a27=(a23*a27);
  a25=(a07*a02);
  a25=(a10*a25);
  a26=(a15*a26);
  a25=(a25+a26);
  a25=(a03*a25);
  a27=(a27-a25);
  a06=(a14*a06);
  a27=(a27+a06);
  if (res[2]!=0) res[2][5]=a27;
  a27=(1./a09);
  a24=(a24/a09);
  a24=(a27-a24);
  if (res[2]!=0) res[2][6]=a24;
  a02=(a02/a09);
  a02=(-a02);
  if (res[2]!=0) res[2][7]=a02;
  a02=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][8]=a02;
  a24=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][9]=a24;
  a06=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][10]=a06;
  a25=arg[2]? arg[2][15] : 0;
  a26=(a15*a25);
  a28=(a05*a26);
  a28=(a10*a28);
  a16=arg[2]? arg[2][14] : 0;
  a17=(a12*a16);
  a29=(a08*a17);
  a28=(a28-a29);
  a29=(a10*a16);
  a30=(a04*a29);
  a28=(a28+a30);
  a28=(a03*a28);
  a02=(a14*a02);
  a28=(a28+a02);
  if (res[2]!=0) res[2][11]=a28;
  a26=(a04*a26);
  a26=(a10*a26);
  a28=(a13*a17);
  a26=(a26-a28);
  a29=(a05*a29);
  a26=(a26-a29);
  a26=(a03*a26);
  a24=(a14*a24);
  a26=(a26+a24);
  if (res[2]!=0) res[2][12]=a26;
  a26=arg[2]? arg[2][8] : 0;
  a26=(a19*a26);
  a24=arg[2]? arg[2][9] : 0;
  a24=(a21*a24);
  a26=(a26+a24);
  a24=arg[2]? arg[2][10] : 0;
  a24=(a22*a24);
  a26=(a26+a24);
  a26=(a26/a20);
  a26=(a18*a26);
  a26=(a23*a26);
  a24=(a07*a25);
  a24=(a10*a24);
  a17=(a15*a17);
  a24=(a24+a17);
  a24=(a03*a24);
  a26=(a26-a24);
  a06=(a14*a06);
  a26=(a26+a06);
  if (res[2]!=0) res[2][13]=a26;
  a16=(a16/a09);
  a16=(-a16);
  if (res[2]!=0) res[2][14]=a16;
  a25=(a25/a09);
  a27=(a27-a25);
  if (res[2]!=0) res[2][15]=a27;
  a27=arg[2]? arg[2][19] : 0;
  if (res[2]!=0) res[2][16]=a27;
  a25=arg[2]? arg[2][20] : 0;
  if (res[2]!=0) res[2][17]=a25;
  a16=arg[2]? arg[2][21] : 0;
  if (res[2]!=0) res[2][18]=a16;
  a26=arg[2]? arg[2][23] : 0;
  a06=(a15*a26);
  a24=(a05*a06);
  a24=(a10*a24);
  a17=arg[2]? arg[2][22] : 0;
  a12=(a12*a17);
  a08=(a08*a12);
  a24=(a24-a08);
  a08=(a10*a17);
  a29=(a04*a08);
  a24=(a24+a29);
  a24=(a03*a24);
  a27=(a14*a27);
  a24=(a24+a27);
  a11=(a11+a24);
  if (res[2]!=0) res[2][19]=a11;
  a04=(a04*a06);
  a04=(a10*a04);
  a13=(a13*a12);
  a04=(a04-a13);
  a05=(a05*a08);
  a04=(a04-a05);
  a04=(a03*a04);
  a25=(a14*a25);
  a04=(a04+a25);
  a00=(a00+a04);
  if (res[2]!=0) res[2][20]=a00;
  a00=arg[2]? arg[2][16] : 0;
  a19=(a19*a00);
  a00=arg[2]? arg[2][17] : 0;
  a21=(a21*a00);
  a19=(a19+a21);
  a21=arg[2]? arg[2][18] : 0;
  a22=(a22*a21);
  a19=(a19+a22);
  a19=(a19/a20);
  a18=(a18*a19);
  a23=(a23*a18);
  a07=(a07*a26);
  a10=(a10*a07);
  a15=(a15*a12);
  a10=(a10+a15);
  a03=(a03*a10);
  a23=(a23-a03);
  a14=(a14*a16);
  a23=(a23+a14);
  a01=(a01+a23);
  if (res[2]!=0) res[2][21]=a01;
  a17=(a17/a09);
  a17=(-a17);
  if (res[2]!=0) res[2][22]=a17;
  a26=(a26/a09);
  a26=(-a26);
  if (res[2]!=0) res[2][23]=a26;
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void uav_tethered_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int uav_tethered_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int uav_tethered_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real uav_tethered_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* uav_tethered_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* uav_tethered_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* uav_tethered_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* uav_tethered_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int uav_tethered_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
