/frame_aligner:
  ros__parameters:
    world_frame: "world"
    boat_frame: "boat/base_link"
    drone_frame: "drone/base_link"
    
    boat_odom_topic: "/boat/ground_truth/odometry"
    drone_odom_topic: "/drone/ground_truth/odometry"
    drone_z_offset: 0.265
