import os
from ament_index_python.packages import get_package_share_directory
from launch import LaunchDescription
from launch_ros.actions import Node

def generate_launch_description():
    # Get package share directory
    pkg_usv_mpc = get_package_share_directory('usv_mpc')
    
    # Path to YAML config file
    usv_mpc_config = os.path.join(pkg_usv_mpc, 'config', 'usv_mpc.yaml')

    # 1. Boat MPC Node
    usv_mpc_node = Node(
        package='usv_mpc',
        executable='usv_mpc_node',
        name='usv_mpc_node',
        output='screen',
        parameters=[
            usv_mpc_config,
            {'use_sim_time': True}
        ],
        remappings=[
            ('odom', '/boat/ground_truth/odometry'),
            ('cmd_vel', '/cmd_vel'),
            ('reference_path', '/usv/reference_path'),
            ('target_position', '/usv/target_position')
        ]
    )

    # 2. Bridge cmd_vel from ROS 2 to Gazebo Sim (/model/boat/cmd_vel)
    # This ensures that the velocity commands generated by the MPC node reach the Gazebo vehicle model.
    cmd_vel_bridge = Node(
        package='ros_gz_bridge',
        executable='parameter_bridge',
        name='usv_cmd_vel_bridge',
        arguments=[
            '/model/boat/cmd_vel@geometry_msgs/msg/Twist]gz.msgs.Twist'
        ],
        remappings=[
            ('/model/boat/cmd_vel', '/cmd_vel')
        ],
        output='screen'
    )

    return LaunchDescription([
        usv_mpc_node,
        cmd_vel_bridge
    ])
