/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) usv_dynamic_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fabs CASADI_PREFIX(fabs)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sign CASADI_PREFIX(sign)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_fabs(casadi_real x) {
/* Pre-c99 compatibility */
#if __STDC_VERSION__ < 199901L
  return x>0 ? x : -x;
#else
  return fabs(x);
#endif
}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {9, 1, 1};

/* usv_dynamic_expl_vde_adj:(i0[6],i1[6],i2[3],i3[0])->(o0[9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  a01=arg[0]? arg[0][2] : 0;
  a02=cos(a01);
  a03=arg[0]? arg[0][3] : 0;
  a04=arg[1]? arg[1][1] : 0;
  a05=(a03*a04);
  a05=(a02*a05);
  a01=sin(a01);
  a06=arg[0]? arg[0][4] : 0;
  a07=(a06*a04);
  a07=(a01*a07);
  a05=(a05-a07);
  a07=arg[1]? arg[1][0] : 0;
  a08=(a06*a07);
  a08=(a02*a08);
  a05=(a05-a08);
  a08=(a03*a07);
  a08=(a01*a08);
  a05=(a05-a08);
  if (res[0]!=0) res[0][2]=a05;
  a05=(a01*a04);
  a08=arg[0]? arg[0][5] : 0;
  a09=arg[1]? arg[1][4] : 0;
  a10=(a08*a09);
  a11=1.6597000000000000e+02;
  a00=(a03<a00);
  a12=1.5768000000000001e+02;
  a12=(a00?a12:0);
  a00=(!a00);
  a13=140.;
  a00=(a00?a13:0);
  a12=(a12+a00);
  a00=casadi_fabs(a03);
  a00=(a12*a00);
  a11=(a11+a00);
  a00=3.4502984508159957e-03;
  a13=arg[1]? arg[1][3] : 0;
  a14=(a00*a13);
  a11=(a11*a14);
  a10=(a10+a11);
  a11=casadi_sign(a03);
  a15=(a03*a14);
  a12=(a12*a15);
  a11=(a11*a12);
  a10=(a10+a11);
  a05=(a05-a10);
  a10=(a02*a07);
  a05=(a05+a10);
  if (res[0]!=0) res[0][3]=a05;
  a05=(a08*a13);
  a10=9.2849999999999994e+01;
  a11=1.0242000000000000e+02;
  a12=casadi_fabs(a06);
  a12=(a11*a12);
  a10=(a10+a12);
  a00=(a00*a09);
  a10=(a10*a00);
  a12=casadi_sign(a06);
  a15=(a06*a00);
  a11=(a11*a15);
  a12=(a12*a11);
  a10=(a10+a12);
  a05=(a05-a10);
  a02=(a02*a04);
  a05=(a05+a02);
  a01=(a01*a07);
  a05=(a05-a01);
  if (res[0]!=0) res[0][4]=a05;
  a06=(a06*a13);
  a13=4.0075999999999999e+02;
  a05=1.0691500000000001e+03;
  a01=casadi_fabs(a08);
  a01=(a05*a01);
  a13=(a13+a01);
  a01=1.6666666666666668e-03;
  a07=arg[1]? arg[1][5] : 0;
  a01=(a01*a07);
  a13=(a13*a01);
  a07=casadi_sign(a08);
  a08=(a08*a01);
  a05=(a05*a08);
  a07=(a07*a05);
  a13=(a13+a07);
  a03=(a03*a09);
  a13=(a13+a03);
  a06=(a06-a13);
  a13=arg[1]? arg[1][2] : 0;
  a06=(a06+a13);
  if (res[0]!=0) res[0][5]=a06;
  if (res[0]!=0) res[0][6]=a14;
  if (res[0]!=0) res[0][7]=a00;
  if (res[0]!=0) res[0][8]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_dynamic_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int usv_dynamic_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_dynamic_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_dynamic_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int usv_dynamic_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void usv_dynamic_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void usv_dynamic_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void usv_dynamic_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int usv_dynamic_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int usv_dynamic_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real usv_dynamic_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_dynamic_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* usv_dynamic_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_dynamic_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* usv_dynamic_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int usv_dynamic_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int usv_dynamic_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
